// Generates styles/theme.css from Apple's system palette.
// Run with: npm run build:tokens

import { writeFileSync, mkdirSync } from "node:fs"
import { hexToOklch, oklchToHex, contrast } from "./color.mjs"
import { SYSTEM, GRAY, L_SCALE, C_SCALE, STEPS } from "./palette.mjs"

/** Build an 11-step ramp whose anchor step reproduces the Apple colour exactly.
 *
 * The anchor snaps to whichever step matches its own perceptual lightness — Apple
 * blue is a 600, Apple yellow is a 200 — and the remaining steps are then spread
 * between the anchor and the ends of the ramp. Spreading rather than using a fixed
 * lightness scale is what keeps yellow-50 a near-white tint instead of a cream. */
function ramp(anchorHex) {
  const [aL, aC, aH] = hexToOklch(anchorHex)

  const anchorStep = STEPS.reduce((best, s) =>
    Math.abs(L_SCALE[s] - aL) < Math.abs(L_SCALE[best] - aL) ? s : best
  )
  const anchorIndex = STEPS.indexOf(anchorStep)

  const LIGHT_END = 0.985
  const DARK_END = 0.235

  const out = { [anchorStep]: anchorHex.toUpperCase() }

  // Tints: walk up toward white, shedding chroma faster than lightness.
  const lighter = anchorIndex
  for (let k = 1; k <= lighter; k++) {
    const t = k / lighter
    const L = aL + (LIGHT_END - aL) * Math.pow(t, 0.9)
    const C = aC * (0.14 + 0.86 * Math.pow(1 - t, 1.35))
    out[STEPS[anchorIndex - k]] = oklchToHex([L, C, aH])
  }

  // Shades: walk down toward near-black, holding chroma much longer.
  const darker = STEPS.length - 1 - anchorIndex
  for (let k = 1; k <= darker; k++) {
    const t = k / darker
    const L = aL + (DARK_END - aL) * Math.pow(t, 1.02)
    const C = aC * (1 - 0.45 * Math.pow(t, 1.6))
    out[STEPS[anchorIndex + k]] = oklchToHex([L, C, aH])
  }

  return { steps: out, anchorStep }
}

const ramps = {}
const anchorSteps = {}
for (const [name, { light }] of Object.entries(SYSTEM)) {
  const { steps, anchorStep } = ramp(light)
  ramps[name] = steps
  anchorSteps[name] = anchorStep
}

/** Black or white, whichever reads better on the given background. */
const onColor = (hex) => (contrast(hex, "#FFFFFF") >= contrast(hex, "#000000") ? "#FFFFFF" : "#000000")

const HUES = Object.keys(SYSTEM)
let tokenCount = 0
const count = (block) => {
  tokenCount += (block.match(/^\s*--/gm) || []).length
  return block
}

const rampBlock = HUES.map((h) =>
  `  /* ${h} — anchored on ${h === "lime" ? "the template lime" : `Apple system ${h}`} at ${anchorSteps[h]} */\n` +
  STEPS.map((s) => `  --color-${h}-${s}: ${ramps[h][s]};`).join("\n")
).join("\n\n")

const grayBlock = Object.entries(GRAY)
  .map(([s, hex]) => `  --color-gray-${s}: ${hex};`)
  .join("\n")

const systemBlock = Object.entries(SYSTEM)
  .map(([n, v]) => `  --color-system-${n}: ${v.light};\n  --color-system-${n}-dark: ${v.dark};`)
  .join("\n")

const css = `/* ------------------------------------------------------------------
 * theme.css — generated by scripts/build-tokens.mjs. Do not edit by hand.
 *
 * Layer 1  @theme         primitives: ramps, radii, shadows, motion, type
 * Layer 2  @theme inline  semantic tokens, mapped to runtime variables
 * Layer 3  :root          semantic values, light appearance
 * Layer 4  .dark          semantic values, dark appearance
 * ------------------------------------------------------------------ */

@theme {
${count(`  /* ---- Type ---------------------------------------------------- */
  --font-sans: -apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text",
    "Inter", "Helvetica Neue", system-ui, sans-serif;
  --font-mono: ui-monospace, "SF Mono", SFMono-Regular, "JetBrains Mono", Menlo,
    Consolas, monospace;
  --font-rounded: ui-rounded, "SF Pro Rounded", -apple-system, system-ui, sans-serif;`)}

${count(`  /* ---- Neutrals — Apple's six system greys, as one ramp ---------- */
${grayBlock}`)}

${count(rampBlock)}

${count(`  /* ---- Apple system colours, verbatim ---------------------------- */
${systemBlock}`)}

${count(`  /* ---- Type scale — Apple's text styles, in rem -------------------- */
  --text-caption2: 0.6875rem;
  --text-caption2--line-height: 1.0625rem;
  --text-caption2--letter-spacing: 0.006em;
  --text-caption1: 0.75rem;
  --text-caption1--line-height: 1.125rem;
  --text-caption1--letter-spacing: 0em;
  --text-footnote: 0.8125rem;
  --text-footnote--line-height: 1.25rem;
  --text-footnote--letter-spacing: -0.006em;
  --text-subheadline: 0.9375rem;
  --text-subheadline--line-height: 1.4375rem;
  --text-subheadline--letter-spacing: -0.014em;
  --text-callout: 1rem;
  --text-callout--line-height: 1.5rem;
  --text-callout--letter-spacing: -0.02em;
  --text-body: 1.0625rem;
  --text-body--line-height: 1.5rem;
  --text-body--letter-spacing: -0.024em;
  --text-headline: 1.0625rem;
  --text-headline--line-height: 1.5rem;
  --text-headline--letter-spacing: -0.024em;
  --text-headline--font-weight: 600;
  --text-title3: 1.25rem;
  --text-title3--line-height: 1.5625rem;
  --text-title3--letter-spacing: -0.026em;
  --text-title2: 1.375rem;
  --text-title2--line-height: 1.75rem;
  --text-title2--letter-spacing: -0.026em;
  --text-title1: 1.75rem;
  --text-title1--line-height: 2.125rem;
  --text-title1--letter-spacing: -0.028em;
  --text-large-title: 2.125rem;
  --text-large-title--line-height: 2.5625rem;
  --text-large-title--letter-spacing: -0.03em;
  --text-display: 3rem;
  --text-display--line-height: 1.06;
  --text-display--letter-spacing: -0.032em;
  --text-display-lg: 4rem;
  --text-display-lg--line-height: 1.02;
  --text-display-lg--letter-spacing: -0.036em;

  --tracking-tightest: -0.036em;
  --tracking-tighter: -0.028em;
  --tracking-tight: -0.018em;
  --tracking-normal: -0.01em;
  --tracking-wide: 0.01em;
  --tracking-widest: 0.06em;`)}

${count(`  /* ---- Radius — Apple's continuous-corner scale ------------------ */
  --radius-xs: 6px;
  --radius-sm: 8px;
  --radius-md: 10px;
  --radius-lg: 12px;
  --radius-xl: 14px;
  --radius-2xl: 18px;
  --radius-3xl: 22px;
  --radius-4xl: 28px;
  --radius-full: 9999px;`)}

${count(`  /* ---- Elevation — short, tight, low-opacity ---------------------- */
  --shadow-xs: 0 1px 1px oklch(0 0 0 / 0.04), 0 1px 2px oklch(0 0 0 / 0.04);
  --shadow-sm: 0 1px 2px oklch(0 0 0 / 0.05), 0 2px 6px oklch(0 0 0 / 0.05);
  --shadow-md: 0 2px 4px oklch(0 0 0 / 0.05), 0 6px 16px oklch(0 0 0 / 0.07);
  --shadow-lg: 0 4px 8px oklch(0 0 0 / 0.05), 0 12px 32px oklch(0 0 0 / 0.09);
  --shadow-xl: 0 8px 16px oklch(0 0 0 / 0.06), 0 24px 56px oklch(0 0 0 / 0.12);
  --shadow-popover: 0 0 0 0.5px oklch(0 0 0 / 0.08), 0 8px 28px oklch(0 0 0 / 0.14);
  --shadow-inset: inset 0 1px 0 oklch(1 0 0 / 0.6);`)}

${count(`  /* ---- Motion — Apple's spring-ish curves ------------------------ */
  --ease-standard: cubic-bezier(0.4, 0, 0.2, 1);
  --ease-out-quint: cubic-bezier(0.22, 1, 0.36, 1);
  --ease-in-out-quart: cubic-bezier(0.76, 0, 0.24, 1);
  --ease-spring: cubic-bezier(0.34, 1.56, 0.64, 1);
  --duration-instant: 90ms;
  --duration-fast: 150ms;
  --duration-normal: 250ms;
  --duration-slow: 400ms;`)}

${count(`  /* ---- Materials — vibrancy blur radii --------------------------- */
  --blur-thin: 12px;
  --blur-regular: 20px;
  --blur-thick: 32px;
  --blur-chrome: 44px;`)}
}

/* Semantic layer. \`inline\` keeps the reference unresolved so :root and .dark
 * can repoint every token at runtime. */
@theme inline {
${count(`  --color-bg: var(--ui-bg);
  --color-bg-subtle: var(--ui-bg-subtle);
  --color-bg-muted: var(--ui-bg-muted);
  --color-surface: var(--ui-surface);
  --color-surface-raised: var(--ui-surface-raised);
  --color-surface-sunken: var(--ui-surface-sunken);
  --color-surface-hover: var(--ui-surface-hover);
  --color-overlay: var(--ui-overlay);
  --color-material: var(--ui-material);
  --color-material-thick: var(--ui-material-thick);

  --color-fg: var(--ui-fg);
  --color-fg-secondary: var(--ui-fg-secondary);
  --color-fg-tertiary: var(--ui-fg-tertiary);
  --color-fg-quaternary: var(--ui-fg-quaternary);
  --color-fg-placeholder: var(--ui-fg-placeholder);
  --color-fg-inverted: var(--ui-fg-inverted);

  --color-border: var(--ui-border);
  --color-border-subtle: var(--ui-border-subtle);
  --color-border-strong: var(--ui-border-strong);
  --color-separator: var(--ui-separator);
  --color-separator-opaque: var(--ui-separator-opaque);

  --color-fill: var(--ui-fill);
  --color-fill-secondary: var(--ui-fill-secondary);
  --color-fill-tertiary: var(--ui-fill-tertiary);
  --color-fill-quaternary: var(--ui-fill-quaternary);

  --color-accent: var(--ui-accent);
  --color-accent-hover: var(--ui-accent-hover);
  --color-accent-active: var(--ui-accent-active);
  --color-accent-subtle: var(--ui-accent-subtle);
  --color-accent-muted: var(--ui-accent-muted);
  --color-accent-fg: var(--ui-accent-fg);

  --color-success: var(--ui-success);
  --color-success-subtle: var(--ui-success-subtle);
  --color-success-fg: var(--ui-success-fg);
  --color-warning: var(--ui-warning);
  --color-warning-subtle: var(--ui-warning-subtle);
  --color-warning-fg: var(--ui-warning-fg);
  --color-danger: var(--ui-danger);
  --color-danger-hover: var(--ui-danger-hover);
  --color-danger-subtle: var(--ui-danger-subtle);
  --color-danger-fg: var(--ui-danger-fg);
  --color-info: var(--ui-info);
  --color-info-subtle: var(--ui-info-subtle);
  --color-info-fg: var(--ui-info-fg);

  --color-ring: var(--ui-ring);
  --color-selection: var(--ui-selection);

  --color-chart-1: var(--ui-chart-1);
  --color-chart-2: var(--ui-chart-2);
  --color-chart-3: var(--ui-chart-3);
  --color-chart-4: var(--ui-chart-4);
  --color-chart-5: var(--ui-chart-5);
  --color-chart-6: var(--ui-chart-6);
  --color-chart-7: var(--ui-chart-7);
  --color-chart-8: var(--ui-chart-8);
  --color-chart-grid: var(--ui-chart-grid);
  --color-chart-axis: var(--ui-chart-axis);
  --color-chart-track: var(--ui-chart-track);`)}
}

/* ---- Light appearance ------------------------------------------------ */
:root {
  color-scheme: light;

${count(`  /* Backgrounds — Apple grouped-background hierarchy */
  --ui-bg: #FFFFFF;
  --ui-bg-subtle: ${GRAY[100]};
  --ui-bg-muted: ${GRAY[200]};
  --ui-surface: #FFFFFF;
  --ui-surface-raised: #FFFFFF;
  --ui-surface-sunken: ${GRAY[100]};
  --ui-surface-hover: rgb(120 120 128 / 0.06);
  --ui-overlay: rgb(0 0 0 / 0.24);
  --ui-material: rgb(255 255 255 / 0.72);
  --ui-material-thick: rgb(255 255 255 / 0.86);

  /* Labels */
  --ui-fg: #000000;
  --ui-fg-secondary: rgb(60 60 67 / 0.60);
  --ui-fg-tertiary: rgb(60 60 67 / 0.30);
  --ui-fg-quaternary: rgb(60 60 67 / 0.18);
  --ui-fg-placeholder: rgb(60 60 67 / 0.30);
  --ui-fg-inverted: #FFFFFF;

  /* Separators */
  --ui-border: rgb(60 60 67 / 0.16);
  --ui-border-subtle: rgb(60 60 67 / 0.09);
  --ui-border-strong: rgb(60 60 67 / 0.29);
  --ui-separator: rgb(60 60 67 / 0.29);
  --ui-separator-opaque: #C6C6C8;

  /* Fills */
  --ui-fill: rgb(120 120 128 / 0.20);
  --ui-fill-secondary: rgb(120 120 128 / 0.16);
  --ui-fill-tertiary: rgb(120 120 128 / 0.12);
  --ui-fill-quaternary: rgb(120 120 128 / 0.08);

  /* Accent */
  --ui-accent: ${SYSTEM.blue.light};
  --ui-accent-hover: ${ramps.blue[600]};
  --ui-accent-active: ${ramps.blue[700]};
  --ui-accent-subtle: ${ramps.blue[50]};
  --ui-accent-muted: ${ramps.blue[100]};
  --ui-accent-fg: ${onColor(SYSTEM.blue.light)};

  /* Status */
  --ui-success: ${SYSTEM.green.light};
  --ui-success-subtle: ${ramps.green[50]};
  --ui-success-fg: ${ramps.green[700]};
  --ui-warning: ${SYSTEM.orange.light};
  --ui-warning-subtle: ${ramps.orange[50]};
  --ui-warning-fg: ${ramps.orange[700]};
  --ui-danger: ${SYSTEM.red.light};
  --ui-danger-hover: ${ramps.red[600]};
  --ui-danger-subtle: ${ramps.red[50]};
  --ui-danger-fg: ${ramps.red[700]};
  --ui-info: ${SYSTEM.indigo.light};
  --ui-info-subtle: ${ramps.indigo[50]};
  --ui-info-fg: ${ramps.indigo[700]};

  --ui-ring: ${SYSTEM.blue.light};
  --ui-selection: ${ramps.blue[100]};

  /* Charts */
  --ui-chart-1: ${SYSTEM.lime.light};
  --ui-chart-2: ${SYSTEM.blue.light};
  --ui-chart-3: ${SYSTEM.purple.light};
  --ui-chart-4: ${SYSTEM.pink.light};
  --ui-chart-5: ${SYSTEM.mint.light};
  --ui-chart-6: ${SYSTEM.orange.light};
  --ui-chart-7: ${SYSTEM.indigo.light};
  --ui-chart-8: ${SYSTEM.cyan.light};
  --ui-chart-grid: rgb(60 60 67 / 0.10);
  --ui-chart-axis: rgb(60 60 67 / 0.30);
  --ui-chart-track: rgb(120 120 128 / 0.12);`)}
}

/* ---- Dark appearance ------------------------------------------------- */
.dark {
  color-scheme: dark;

${count(`  --ui-bg: #000000;
  --ui-bg-subtle: ${GRAY[950]};
  --ui-bg-muted: ${GRAY[900]};
  --ui-surface: ${GRAY[950]};
  --ui-surface-raised: ${GRAY[900]};
  --ui-surface-sunken: #000000;
  --ui-surface-hover: rgb(120 120 128 / 0.16);
  --ui-overlay: rgb(0 0 0 / 0.56);
  --ui-material: rgb(28 28 30 / 0.72);
  --ui-material-thick: rgb(28 28 30 / 0.88);

  --ui-fg: #FFFFFF;
  --ui-fg-secondary: rgb(235 235 245 / 0.60);
  --ui-fg-tertiary: rgb(235 235 245 / 0.30);
  --ui-fg-quaternary: rgb(235 235 245 / 0.16);
  --ui-fg-placeholder: rgb(235 235 245 / 0.30);
  --ui-fg-inverted: #000000;

  --ui-border: rgb(235 235 245 / 0.14);
  --ui-border-subtle: rgb(235 235 245 / 0.08);
  --ui-border-strong: rgb(84 84 88 / 0.65);
  --ui-separator: rgb(84 84 88 / 0.65);
  --ui-separator-opaque: #38383A;

  --ui-fill: rgb(120 120 128 / 0.36);
  --ui-fill-secondary: rgb(120 120 128 / 0.32);
  --ui-fill-tertiary: rgb(120 120 128 / 0.24);
  --ui-fill-quaternary: rgb(120 120 128 / 0.18);

  --ui-accent: ${SYSTEM.blue.dark};
  --ui-accent-hover: ${ramps.blue[400]};
  --ui-accent-active: ${ramps.blue[300]};
  --ui-accent-subtle: rgb(10 132 255 / 0.16);
  --ui-accent-muted: rgb(10 132 255 / 0.28);
  --ui-accent-fg: #FFFFFF;

  --ui-success: ${SYSTEM.green.dark};
  --ui-success-subtle: rgb(48 209 88 / 0.16);
  --ui-success-fg: ${ramps.green[300]};
  --ui-warning: ${SYSTEM.orange.dark};
  --ui-warning-subtle: rgb(255 159 10 / 0.16);
  --ui-warning-fg: ${ramps.orange[300]};
  --ui-danger: ${SYSTEM.red.dark};
  --ui-danger-hover: ${ramps.red[400]};
  --ui-danger-subtle: rgb(255 69 58 / 0.16);
  --ui-danger-fg: ${ramps.red[300]};
  --ui-info: ${SYSTEM.indigo.dark};
  --ui-info-subtle: rgb(94 92 230 / 0.18);
  --ui-info-fg: ${ramps.indigo[300]};

  --ui-ring: ${SYSTEM.blue.dark};
  --ui-selection: rgb(10 132 255 / 0.35);

  --ui-chart-1: ${SYSTEM.lime.dark};
  --ui-chart-2: ${SYSTEM.blue.dark};
  --ui-chart-3: ${SYSTEM.purple.dark};
  --ui-chart-4: ${SYSTEM.pink.dark};
  --ui-chart-5: ${SYSTEM.mint.dark};
  --ui-chart-6: ${SYSTEM.orange.dark};
  --ui-chart-7: ${SYSTEM.indigo.dark};
  --ui-chart-8: ${SYSTEM.cyan.dark};
  --ui-chart-grid: rgb(235 235 245 / 0.09);
  --ui-chart-axis: rgb(235 235 245 / 0.30);
  --ui-chart-track: rgb(120 120 128 / 0.24);`)}
}
`

mkdirSync("styles", { recursive: true })
writeFileSync("styles/theme.css", css)

// Emit the same data as JSON so the docs pages can render the palette
// without re-parsing CSS.
mkdirSync("data", { recursive: true })
writeFileSync(
  "data/palette.json",
  JSON.stringify({ ramps, anchorSteps, gray: GRAY, system: SYSTEM, steps: STEPS }, null, 2)
)

console.log(`styles/theme.css — ${tokenCount} tokens across ${Object.keys(ramps).length + 1} ramps`)
